import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

import { ThemeProvider } from "./context/themeContext";
import Main from "./Main";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anees",
  description: "Generated by Anees",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <Main>
        <Navbar/>
        {children}
        <Footer/>
        </Main>
        </ThemeProvider>
        </body>
    </html>
  );
}
