export const data=[
    { id:1, title:"How much do you usually charge for a website?", description:"Testimonials are valuable because they provide social proof and reassurance to others who are considering engaging with the same product, service, or event."},
    { id:2, title:"How long does a project take to complete?", description:"Testimonials are valuable because they provide social proof and reassurance to others who are considering engaging with the same product, service, or event."},
    { id:3, title:"Do you have team or work alone?", description:"Testimonials are valuable because they provide social proof and reassurance to others who are considering engaging with the same product, service, or event."},
    { id:4, title:"Are you available for collaboration?", description:"Testimonials are valuable because they provide social proof and reassurance to others who are considering engaging with the same product, service, or event."},
    { id:5, title:"How long does a project take to complete?", description:"Testimonials are valuable because they provide social proof and reassurance to others who are considering engaging with the same product, service, or event."},
    { id:6, title:"How long does a project take to complete?", description:"Testimonials are valuable because they provide social proof and reassurance to others who are considering engaging with the same product, service, or event."},
    { id:7, title:"How long does a project take to complete?", description:"Testimonials are valuable because they provide social proof and reassurance to others who are considering engaging with the same product, service, or event."},
    { id:8, title:"How long does a project take to complete?", description:"Testimonials are valuable because they provide social proof and reassurance to others who are considering engaging with the same product, service, or event."},
]